import { z } from "zod";

import { paise, PLATFORM_CURRENCY } from "../money";

import type { Paise } from "../money";

/** Database ids are uuid v4 generated by Postgres — see docs/CONVENTIONS.md. */
export const uuidSchema = z.uuid();

/**
 * `bigserial` keys (`queue_events`, `audit_log`) arrive as JSON numbers from
 * PostgREST and must stay integers.
 */
export const serialIdSchema = z.number().int().positive();

/** All timestamps are `timestamptz` stored UTC. */
export const timestampSchema = z.iso.datetime({ offset: true });

/**
 * Money on the wire. Parsing produces a branded `Paise`, so an unvalidated
 * number from a gateway callback cannot reach a money helper.
 */
export const paiseSchema: z.ZodType<Paise> = z
  .number()
  .int("Amounts are integer paise, never a fraction")
  .nonnegative()
  .transform((n) => paise(n));

export const currencySchema = z.literal(PLATFORM_CURRENCY);

/** Indian mobile number, the identity anchor for patient auth (PRD §10). */
export const phoneSchema = z
  .string()
  .trim()
  .regex(/^(?:\+91)?[6-9]\d{9}$/, "Enter a 10-digit Indian mobile number");

/** Normalises to E.164 so the database only ever stores one representation. */
export const normalisePhone = (raw: string): string => {
  const digits = raw.replace(/\D/g, "");
  const last10 = digits.slice(-10);
  return `+91${last10}`;
};

export const e164PhoneSchema = phoneSchema.transform(normalisePhone);

/**
 * Idempotency key for Edge Function calls. Module 9 requires that retrying a
 * checkout never creates a second order, and PRD §9 Phase 0 exits on
 * "idempotency proven in staging" — so the key is part of the contract from
 * the start rather than bolted on.
 */
export const idempotencyKeySchema = z.string().min(16).max(128);

export const paginationSchema = z.object({
  limit: z.number().int().min(1).max(100).default(20),
  cursor: z.string().optional(),
});

export type Pagination = z.infer<typeof paginationSchema>;
