/**
 * Enum re-exports.
 *
 * Every value in this file is derived from `db.types.ts`, i.e. from the
 * database. Nothing here is hand-typed, because a hand-typed enum is how
 * `StatusBadge` ends up rendering a status the database never emits
 * (DESIGN.md §5, docs/CONVENTIONS.md §5).
 *
 * Two things come out of the generator and both are used here:
 *
 *   - `Database["public"]["Enums"]` — the *types*, for exhaustive switches.
 *   - `Constants.public.Enums`      — the *runtime* member arrays, for anything
 *     that has to iterate: a badge map, a filter chip row, a `<select>`.
 *
 * The Module 2 plan assumed the runtime lists would need a second generated
 * file. They do not — `supabase gen types` already emits `Constants` — so there
 * is one generated artifact, not two. See docs/DATA-MODEL.md §8.
 */

import { Constants } from "./db.types";

import type { Database } from "./db.types";

/** Every enum the public schema defines, keyed by its Postgres type name. */
export type DbEnums = Database["public"]["Enums"];

/** `DbEnum<"appointment_status">` → the union of that enum's members. */
export type DbEnum<K extends keyof DbEnums> = DbEnums[K];

/**
 * Runtime members for every database enum, keyed by Postgres type name.
 * Regenerated by `pnpm db:types`; never edited.
 */
export const DB_ENUM_VALUES = Constants.public.Enums;

export type DbEnumName = keyof typeof DB_ENUM_VALUES;

// ---------------------------------------------------------------------------
// Named aliases
// ---------------------------------------------------------------------------
// `Database["public"]["Enums"]["appointment_status"]` is correct and unreadable.
// These are the names the rest of the codebase uses; they are aliases, not
// declarations, so they cannot drift from the database.

export type AppointmentStatus = DbEnum<"appointment_status">;
export type TokenStatus = DbEnum<"token_status">;
export type PaymentStatus = DbEnum<"payment_status">;
export type StaffRole = DbEnum<"staff_role">;
export type QueueEventType = DbEnum<"queue_event_type">;
export type AppointmentSource = DbEnum<"appointment_source">;
export type SessionStatus = DbEnum<"session_status">;
export type OutboxStatus = DbEnum<"outbox_status">;
export type NotificationChannel = DbEnum<"notification_channel">;
export type FollowUpStatus = DbEnum<"follow_up_status">;

// ---------------------------------------------------------------------------
// Runtime member lists
// ---------------------------------------------------------------------------
// A component that maps over one of these and a component that switches on the
// matching type cannot disagree: both come from the same migration.

export const APPOINTMENT_STATUSES: readonly AppointmentStatus[] =
  DB_ENUM_VALUES.appointment_status;
export const TOKEN_STATUSES: readonly TokenStatus[] = DB_ENUM_VALUES.token_status;
export const PAYMENT_STATUSES: readonly PaymentStatus[] = DB_ENUM_VALUES.payment_status;
export const STAFF_ROLES: readonly StaffRole[] = DB_ENUM_VALUES.staff_role;
export const QUEUE_EVENT_TYPES: readonly QueueEventType[] =
  DB_ENUM_VALUES.queue_event_type;
export const APPOINTMENT_SOURCES: readonly AppointmentSource[] =
  DB_ENUM_VALUES.appointment_source;
export const SESSION_STATUSES: readonly SessionStatus[] = DB_ENUM_VALUES.session_status;
export const OUTBOX_STATUSES: readonly OutboxStatus[] = DB_ENUM_VALUES.outbox_status;
export const NOTIFICATION_CHANNELS: readonly NotificationChannel[] =
  DB_ENUM_VALUES.notification_channel;
export const FOLLOW_UP_STATUSES: readonly FollowUpStatus[] =
  DB_ENUM_VALUES.follow_up_status;

// ---------------------------------------------------------------------------
// Terminal states
// ---------------------------------------------------------------------------
// Mirrors `appointment_transitions` / `token_transitions`: a status with no
// outgoing row is terminal. Duplicated here because a client needs to answer
// "can this still change?" without a round trip — `transitions.test.sql` asserts
// the database agrees, so the duplication cannot rot silently.

export const TERMINAL_APPOINTMENT_STATUSES: readonly AppointmentStatus[] = [
  "COMPLETED",
  "EXPIRED",
  "CANCELLED",
  "NO_SHOW",
  "PAYMENT_FAILED",
];

export const TERMINAL_TOKEN_STATUSES: readonly TokenStatus[] = [
  "COMPLETED",
  "NO_SHOW",
  "CANCELLED",
];

/** True when an appointment can no longer change state. */
export const isTerminalAppointmentStatus = (status: AppointmentStatus): boolean =>
  TERMINAL_APPOINTMENT_STATUSES.includes(status);

/** True when a token can no longer change state. */
export const isTerminalTokenStatus = (status: TokenStatus): boolean =>
  TERMINAL_TOKEN_STATUSES.includes(status);

// ---------------------------------------------------------------------------
// Narrowing
// ---------------------------------------------------------------------------

/**
 * Narrows an untrusted string to a member of a database enum.
 *
 * Use at every boundary where a status arrives as text — a deep link, a push
 * payload, a webhook body. Inside the app a status is always a typed union;
 * this is where it becomes one.
 */
export const isDbEnumValue = <K extends DbEnumName>(
  name: K,
  value: unknown,
): value is DbEnums[K] =>
  typeof value === "string" &&
  (DB_ENUM_VALUES[name] as readonly string[]).includes(value);
