/**
 * Generates the three artifacts the two apps actually consume.
 *
 * DESIGN.md §1 says to mirror the tokens into `tailwind.config` and the mobile
 * theme "rather than retyping" them. This is that mirror. A human copying hex
 * values into two config files is precisely the drift DESIGN.md §7 exists to
 * prevent — it works on the day it is done and diverges quietly thereafter.
 *
 * Three outputs rather than one because the consumers cannot all read the same
 * thing:
 *
 *   tailwind-preset.cjs   Tailwind resolves its config in CommonJS, before any
 *                         TypeScript transform has run.
 *   css-variables.css     shadcn themes through CSS custom properties, in the
 *                         channel-triplet HSL form its own templates expect.
 *   tokens.native.ts      Reanimated worklets execute on the UI thread and
 *                         cannot read CSS variables, so mobile needs literals.
 *
 * Run by `pnpm --filter @rural-opd/tokens build`, and ahead of both apps via
 * Turborepo's `^build` dependency.
 */

import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { colors } from "./src/colors.js";
import { elevation } from "./src/elevation.js";
import { motion } from "./src/motion.js";
import { radii } from "./src/radii.js";
import { MIN_TOUCH_TARGET, spacing, TOUCH_HIT_SLOP } from "./src/spacing.js";
import { fontSize, fontWeight, lineHeight } from "./src/typography.js";

const HERE = dirname(fileURLToPath(import.meta.url));
const DIST = resolve(HERE, "dist");

const BANNER = `/**
 * GENERATED by packages/tokens/build.ts — do not edit.
 *
 * Edit packages/tokens/src/*.ts and re-run \`pnpm --filter @rural-opd/tokens build\`.
 * A hand-edit here is undone by the next build, and in the meantime the two
 * surfaces disagree, which is the one thing this package exists to prevent.
 */`;

const CSS_BANNER = BANNER.replace("/**", "/*").replace(" */", " */");

// ---------------------------------------------------------------------------
// Colour flattening
// ---------------------------------------------------------------------------

/**
 * `{ primary: { green } }` becomes `{ "primary-green": "#187D51" }`, so the
 * Tailwind class is `bg-primary-green` and reads the way the token is named.
 *
 * Dot-nested Tailwind colours would give `bg-primary-green` too, but they also
 * make `primary` itself a valid class name resolving to nothing useful. Flat
 * keys mean every class that exists corresponds to exactly one token.
 */
function flattenColors(
  input: Record<string, unknown>,
  prefix = "",
): Record<string, string> {
  const out: Record<string, string> = {};
  for (const [key, value] of Object.entries(input)) {
    // camelCase to kebab, so `text.onFill` becomes `text-on-fill` and the CSS
    // custom property matches the casing of every other one. A `--text-onFill`
    // among a dozen kebab-case siblings is the kind of inconsistency that gets
    // mistyped once and debugged for an hour.
    const kebab = key.replace(/([a-z0-9])([A-Z])/g, "$1-$2").toLowerCase();
    const name = prefix ? `${prefix}-${kebab}` : kebab;
    if (typeof value === "string") {
      out[name] = value;
    } else if (value && typeof value === "object") {
      Object.assign(out, flattenColors(value as Record<string, unknown>, name));
    }
  }
  return out;
}

const flatColors = flattenColors(colors);

// ---------------------------------------------------------------------------
// 1. Tailwind preset
// ---------------------------------------------------------------------------

/**
 * `theme`, not `theme.extend`. This is the whole trick of the module.
 *
 * Extending keeps Tailwind's defaults alive alongside ours, so `bg-red-500`,
 * `rounded-md` and `p-5` all still work and DESIGN.md §3's "compose from this
 * scale" stays a request. Replacing deletes them: an off-scale class generates
 * no CSS at all, so the element renders visibly unstyled and the mistake is
 * caught in the browser rather than in review.
 *
 * The cost is that genuinely useful defaults go too — `transparent` and
 * `current` are re-added below because a border-less or inherited colour is a
 * real need and not a palette decision.
 */
function tailwindPreset(): string {
  const theme = {
    colors: {
      transparent: "transparent",
      current: "currentColor",
      ...flatColors,
    },
    spacing: Object.fromEntries(Object.entries(spacing).map(([k, v]) => [k, `${v}px`])),
    borderRadius: Object.fromEntries(
      Object.entries(radii).map(([k, v]) => [k, v === 9999 ? "9999px" : `${v}px`]),
    ),
    fontSize: Object.fromEntries(
      Object.entries(fontSize).map(([k, v]) => [
        k,
        // Tailwind's tuple form pins a line height to every size, so a size can
        // never be used without one. DESIGN.md §2 sets 1.4 as the floor for body
        // text, and `tight` is that floor.
        [`${v}px`, { lineHeight: String(lineHeight.tight) }],
      ]),
    ),
    fontWeight: Object.fromEntries(Object.entries(fontWeight)),
    boxShadow: elevation.web,

    // Replacing `colors` is not quite enough on its own. A handful of Tailwind
    // theme keys carry their own hardcoded `DEFAULT` that does not derive from
    // the palette, so they survive the replacement and quietly reintroduce
    // colours from a design system this product is not using:
    //
    //   border    Tailwind's gray-200, so a bare `border` is not border.subtle
    //   ring      blue-500, so every default focus ring is the wrong blue
    //   ring-offset  #fff, which is not surface.base
    //
    // The focus ring is the one that matters. It is the affordance a keyboard
    // or switch user navigates by (DESIGN.md §6), and a default-blue ring on a
    // green button is both off-palette and lower contrast than the token that
    // was designed for it.
    borderColor: { DEFAULT: colors.border.subtle, ...flatColors },
    ringColor: { DEFAULT: colors.primary.blue, ...flatColors },
    ringOffsetColor: { DEFAULT: colors.surface.base, ...flatColors },
    // Not a spacing value: the 44px floor is a hit-area rule from DESIGN.md §3,
    // and giving it its own scale means `min-w-touch` reads as the rule it is.
    minWidth: { touch: `${MIN_TOUCH_TARGET}px` },
    minHeight: { touch: `${MIN_TOUCH_TARGET}px` },

    // The press scale as a named class, so the web button can write
    // `active:scale-press` instead of `active:scale-[0.97]`.
    //
    // Added because the arbitrary-value lint rule rejected the hardcoded
    // version — correctly. 0.97 is a motion token, and a copy of it living in a
    // class string is the same transcription problem as a copied hex: it works,
    // and it stops matching the mobile spring the day either is tuned.
    scale: {
      100: "1",
      press: String(motion.buttonPress.toScale),
    },
  };

  // The one place `extend` is correct, and worth being precise about rather
  // than treating "never extend" as the rule.
  //
  // Replacing exists to *delete* wrong values — an off-scale `p-5` or an
  // off-palette `bg-red-500` has to stop working. Tailwind's animation keys hold
  // no such values: `animate-spin` is a mechanism, not a design decision, and
  // deleting it would only push the next spinner into a hand-written keyframe.
  // So the scales are replaced and the animations are extended.
  //
  // The shimmer duration is read from `motion.shimmer` rather than typed here,
  // which is what makes DESIGN.md §4's "~1.2s loop" one number both surfaces
  // animate to.
  const extend = {
    keyframes: {
      shimmer: {
        // Opacity rather than a travelling gradient highlight. That effect needs
        // a `background-size` trick React Native cannot reproduce, and a shimmer
        // that exists on only one surface is exactly the drift §7 is about.
        "0%, 100%": { opacity: "1" },
        "50%": { opacity: "0.55" },
      },
    },
    animation: {
      shimmer: `shimmer ${motion.shimmer.duration}ms ease-in-out infinite`,
    },
  };

  return `${BANNER}\n\nmodule.exports = ${JSON.stringify({ theme: { ...theme, extend } }, null, 2)};\n`;
}

// ---------------------------------------------------------------------------
// 2. CSS variables for shadcn
// ---------------------------------------------------------------------------

function toHsl(hex: string): string {
  const body = hex.slice(1);
  const r = parseInt(body.slice(0, 2), 16) / 255;
  const g = parseInt(body.slice(2, 4), 16) / 255;
  const b = parseInt(body.slice(4, 6), 16) / 255;

  const max = Math.max(r, g, b);
  const min = Math.min(r, g, b);
  const l = (max + min) / 2;
  const d = max - min;

  let h = 0;
  let s = 0;
  if (d !== 0) {
    s = l > 0.5 ? d / (2 - max - min) : d / (max + min);
    if (max === r) h = ((g - b) / d + (g < b ? 6 : 0)) * 60;
    else if (max === g) h = ((b - r) / d + 2) * 60;
    else h = ((r - g) / d + 4) * 60;
  }

  // shadcn's templates interpolate these into `hsl(var(--token))`, so the value
  // is three bare channels and not an `hsl(...)` call.
  return `${Math.round(h)} ${Math.round(s * 100)}% ${Math.round(l * 100)}%`;
}

function cssVariables(): string {
  const lines = Object.entries(flatColors).map(
    ([name, hex]) => `  --${name}: ${toHsl(hex)};`,
  );

  // shadcn components are written against its own vocabulary (`--background`,
  // `--primary`, `--destructive`). Aliasing rather than renaming our tokens means
  // `shadcn add` keeps working untouched, and the mapping is visible in one place
  // instead of being spread through a rewritten globals.css.
  const shadcnAliases = [
    `  --background: ${toHsl(colors.surface.base)};`,
    `  --foreground: ${toHsl(colors.text.primary)};`,
    `  --card: ${toHsl(colors.surface.alt)};`,
    `  --card-foreground: ${toHsl(colors.text.primary)};`,
    `  --popover: ${toHsl(colors.surface.base)};`,
    `  --popover-foreground: ${toHsl(colors.text.primary)};`,
    `  --primary: ${toHsl(colors.primary.green)};`,
    `  --primary-foreground: ${toHsl(colors.text.onFill)};`,
    `  --secondary: ${toHsl(colors.primary.blue)};`,
    `  --secondary-foreground: ${toHsl(colors.text.onFill)};`,
    `  --muted: ${toHsl(colors.surface.alt)};`,
    `  --muted-foreground: ${toHsl(colors.text.muted)};`,
    `  --accent: ${toHsl(colors.accent.teal)};`,
    `  --accent-foreground: ${toHsl(colors.text.onFill)};`,
    `  --destructive: ${toHsl(colors.danger)};`,
    `  --destructive-foreground: ${toHsl(colors.text.onFill)};`,
    `  --border: ${toHsl(colors.border.subtle)};`,
    `  --input: ${toHsl(colors.border.subtle)};`,
    `  --ring: ${toHsl(colors.primary.blue)};`,
    `  --radius: ${radii.card}px;`,
  ];

  // No `.dark` block. DESIGN.md defines a single light palette and MODULE-PLAN
  // §5 keeps dark mode out of V1 — a speculative dark theme would double the
  // contrast matrix for a surface nobody has designed.
  return [
    CSS_BANNER,
    "",
    ":root {",
    "  /* Design tokens, by their own names. */",
    ...lines,
    "",
    "  /* shadcn's vocabulary, aliased onto the tokens above. */",
    ...shadcnAliases,
    "}",
    "",
  ].join("\n");
}

// ---------------------------------------------------------------------------
// 3. Native literals
// ---------------------------------------------------------------------------

function nativeTokens(): string {
  const value = {
    colors,
    spacing,
    radii,
    fontSize,
    lineHeight,
    fontWeight,
    elevation: elevation.native,
    motion,
    MIN_TOUCH_TARGET,
    TOUCH_HIT_SLOP,
  };

  return [
    BANNER,
    "",
    "/* eslint-disable */",
    "",
    `export const nativeTokens = ${JSON.stringify(value, null, 2)} as const;`,
    "",
    "export const nativeColors = nativeTokens.colors;",
    "export const nativeMotion = nativeTokens.motion;",
    "export const nativeSpacing = nativeTokens.spacing;",
    "export const nativeRadii = nativeTokens.radii;",
    "export const nativeElevation = nativeTokens.elevation;",
    "",
  ].join("\n");
}

// ---------------------------------------------------------------------------

mkdirSync(DIST, { recursive: true });
writeFileSync(resolve(DIST, "tailwind-preset.cjs"), tailwindPreset());
writeFileSync(resolve(DIST, "css-variables.css"), cssVariables());
writeFileSync(resolve(DIST, "tokens.native.ts"), nativeTokens());

const count = Object.keys(flatColors).length;
console.log(
  `tokens: wrote dist/tailwind-preset.cjs, dist/css-variables.css, dist/tokens.native.ts (${count} colours)`,
);
